name: 'bump-tf-values'
description: 'Github action to update (bump) the value for a Terraform local within a specified Terraform file formatted with the standard syntax.'
inputs:
  filepath:
    description: 'Filepath containing Terraform file to be modified'
    required: false
    default: 'main.tf'
  varname:
    description: 'Name of the local to be modified'
    required: true
  value:
    description: 'New value to be assigned to the local'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
