name: codecov
on: [push]

jobs:
  staticcheck:
    name: codecov upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          go-version: '1.20'
      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic
      - uses: codecov/codecov-action@v4.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
